FROM node:16 AS builder

WORKDIR /app

COPY package*.json ./
ENV PORT=8080

ARG _FIREBASE_API_KEY
ENV FIREBASE_API_KEY ${_FIREBASE_API_KEY}
ARG _FIREBASE_AUTH_DOMAIN
ENV FIREBASE_AUTH_DOMAIN ${_FIREBASE_AUTH_DOMAIN}
ARG _FIREBASE_DATABASE_URL
ENV FIREBASE_DATABASE_URL ${_FIREBASE_DATABASE_URL}
ARG _FIREBASE_PROJECT_ID
ENV FIREBASE_PROJECT_ID ${_FIREBASE_PROJECT_ID}
ARG _FIREBASE_STORAGE_BUCKET
ENV FIREBASE_STORAGE_BUCKET ${_FIREBASE_STORAGE_BUCKET}
ARG _FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_MESSAGING_SENDER_ID ${_FIREBASE_MESSAGING_SENDER_ID}
ARG _FIREBASE_APP_ID
ENV FIREBASE_APP_ID ${_FIREBASE_APP_ID}
ARG _FIREBASE_MESUREMENT_ID
ENV FIREBASE_MESUREMENT_ID ${_FIREBASE_MESUREMENT_ID}
ARG _ISS
ENV ISS ${_ISS}

RUN npm install

COPY ./ ./

RUN npm run build

CMD ["npm", "run", "start"]
